name: Test self hosted agent

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, default]
    permissions:
      contents: read
    steps:
    - name: summarize
      run: |
        echo "## Summary: " >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        echo "I\'m running on a self hosted agent" >> $GITHUB_STEP_SUMMARY