name: Test ip

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: output
      id: output
      uses: actions/github-script@v7
      with:
        script: |
          const ipv4 = await http.getJson<IPResponse>(
            "https://api.ipify.org?format=json"
          );

          return ipv4.result.ip
        result-encoding: string
    - name: summarize
      env:
        OUTPUT: ${{ steps.output.outputs.result }}
      run: |
        echo "## Summary: " >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        echo "IP: ${OUTPUT}" >> $GITHUB_STEP_SUMMARY