name: Test ip

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: output
      id: output
      run: |
        RESP=$(curl -fsSL "https://api.ipify.org?format=json")
        IPV4=$(jq -r '.ip' <<< ${RESP})
        echo "ip=${IPV4}" >> $GITHUB_OUTPUT
    - name: summarize
      env:
        OUTPUT: ${{ steps.output.outputs.ip }}
      run: |
        echo "## Summary: " >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        echo "IP: ${OUTPUT}" >> $GITHUB_STEP_SUMMARY