name: Test self hosted agent

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, test]
    permissions:
      contents: read
    steps:
    - name: echo
      id: echo
      run: |
        echo "Hello self hosted agent"
        echo "<nil>"
        echo "\"<nil>\""
        echo '"<nil>"'
    - name: summarize
      run: |
        echo "## Summary: " >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.echo.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY