name: Test self hosted agent

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, test]
    permissions:
      contents: read
    steps:
    - name: echo
      run: |
        echo "Hello self hosted agent"
