name: Test escaping

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: output
      id: output
      uses: actions/github-script@v7
      with:
        script: return "Some strings to escape \n<nil>\n\"<nil>\"\n\"\"<nil>\"\"\n'<nil>'\n\'<nil>\'"
        result-encoding: string
    - name: summarize
      env:
        OUTPUT: ${{ steps.output.outputs.result }}
      run: |
        echo "## Summary: " >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        echo "${OUTPUT}" >> $GITHUB_STEP_SUMMARY