name: Test escaping

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: echo
      id: echo
      run: |
        echo "Hello self hosted agent"
        echo "<nil>"
        echo "\"<nil>\""
        echo '"<nil>"'
    - name: output
      id: output
      uses: actions/github-script@v7
      with:
        script: "Hello self hosted agent \n<nil>\n\"<nil>\"\n\"\"<nil>\"\"\n\"\"<nil>\""
        result-encoding: string
    - name: summarize
      run: |
        echo "## Summary: " >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.output.outputs.result }}"" >> $GITHUB_STEP_SUMMARY